# Generated by Django 5.2.6 on 2025-10-26 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_billingconfig_promocode_signimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('signature', 'signature'), ('sig_seal', 'sig_seal'), ('round_seal', 'round_seal')], default='signature', max_length=16)),
                ('mime', models.CharField(default='image/png', max_length=100)),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HiddenDefaultSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to='core.globalsignimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_defaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sign')},
            },
        ),
    ]
