# Generated by Django 5.2.6 on 2025-10-27 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tempstorageconfig_uploadrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('doc_name', models.CharField(blank=True, default='', max_length=200)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_delete_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TempStorageConfig',
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='draft_ttl_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.DeleteModel(
            name='UploadRecord',
        ),
    ]
