# Generated by Django 5.2.6 on 2025-11-01 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_upload_delete_tempstorageconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='price_month',
            field=models.PositiveIntegerField(default=399),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='price_single',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='price_year',
            field=models.PositiveIntegerField(default=3999),
        ),
        migrations.CreateModel(
            name='DocumentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_draft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
