# Generated by Django 5.2.6 on 2026-03-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_subscription_auto_renew_subscription_card_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="downloads_left",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="single_client_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
