# Generated by Django 5.2.6 on 2026-03-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_subscription_downloads_left_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="downloads_left",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
